### PR TITLE
Makes all interpret functions monomorphic

### PR DESCRIPTION
**Pull request by mikesol**
In order to get magic `do` optimizations, we make all interpret functions monomorphic. The consumer of these functions still needs to make their deku tree polymorphic (via `Korok`) as the interpreter is unknown at that point, but once the deku tree hits the interpreter, the interpreter will be monomorphic.

### CODE REVIEW

**Comment by MonoidMusician** [comment]
Unfortunately I don't see a noticeable performance difference with this change :( `Use grammar` still takes ~5 seconds on Chrome, ~4 seconds on FF for the default grammar. I implemented staggered loading and the list of parsing states is the one that takes the most time to load, which makes sense since it has the most content/elements.

**Comment by mikesol** [comment]
> Unfortunately I don't see a noticeable performance difference with this change :( `Use grammar` still takes ~5 seconds on Chrome, ~4 seconds on FF for the default grammar. I implemented staggered loading and the list of parsing states is the one that takes the most time to load, which makes sense since it has the most content/elements.

We're still in the window where we can revert the composability changes. If you have time, could you build the app against [this commit](https://github.com/mikesol/purescript-deku/tree/2c1e35b1b52fefd924eca66f347a63b343e17608) and post the time difference to this thread (probably needs to use the old bolson)? If it's consistently faster with the previous implementation, I'd vote for reverting & keeping hacking at the composability problem on the side.

**Comment by MonoidMusician** [comment]
Mysterious: this morning it was ~1s Chrome without devtools, ~5s with devtools, and ~3-4s FF with or without devtools (on this `monomorphize` branch). Somehow Chrome was much faster all of the sudden, I don't know why.

I just downgraded and it is much faster across the board: ~0.6s Chrome without devtools, ~2 with; <1s FF.

**Comment by mikesol** [comment]
Ok, super helpful ans thanks for doing that work.
Let's revert tomorrow, then. I can prepare the revert branches on Bolson and Deku. Perhaps I can revisit fraggle with new energy after the revert to see if it's usable.

The only downside to reverting is that some of the SSR improvements will be lost, but those can easily be recreated by consulting main pre-revert.

**Pull request closed without merging**
