### PR TITLE
switcherA and switcherA_

### PR DESCRIPTION
**Pull request by purefunctor**

### CODE REVIEW

**Comment by MonoidMusician** [comment]
See #36, #37, #41, and #43.

**Comment by mikesol** [comment]
Nice! I'll get to this in a bit, sorry for missing it.

**Review by mikesol — CHANGES_REQUESTED** [review]
A couple questions:

- Could you update this to use the new `Event` syntax.
- Could the `f` come on the outside of the new `switcher` functions to preserve composability?

**Comment by mikesol** [comment]
Closing this as the syntax has changed a fair bit

**Comment by mikesol** [comment]
Closing this as the syntax has changed a fair bit

**Pull request closed without merging**
